
[SSL]
  # The SSL certificate to use for the proxy.
  Cert = "cert.pem"
  # The SSL key to use for the proxy.
  Key = "key.pem"
  # Determines if SSL is enabled
  Enabled = false

[HTTP]
  Prefix = "/http/"
  Port = 3000

[WS]
  Prefix = "/ws/"

[ICE]
  Prefix = "/ice/"