
[SSL]
  # The SSL certificate to use for the proxy.
  Cert = "cert.pem"
  # The SSL key to use for the proxy.
  Key = "key.pem"
  # Determines if SSL is enabled
  Enabled = false

[SERVER]
  Port = 3000

[HTTP]
  Prefix = "/http/"

[WS]
  Prefix = "/ws/"