
[SSL]
  # The SSL certificate to use for the proxy.
  Cert = "cert.pem"
  # The SSL key to use for the proxy.
  Key = "key.pem"
  # Determines whether the proxy will use SSL and HTTP/2.
  Enabled = false

[Server]
  # The address and port to listen on.
  Addr = ":80"
  # The directory to use for serving static files.
  Path = "static/"
